name: cloundqiandao

on:

  schedule:
    - cron: '27 17 * * *'
  workflow_dispatch:  
jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        ONEPUSH: ${{ secrets.ONEPUSH }}
        USER: ${{ secrets.USER }}
        PWD: ${{ secrets.PWD }}
      
    - name: requirements
      run: |
        pip install -r requirements.txt
        
    - name: Checkin
      run: |
        python Cloud189Checkin.py

