name: cloundqiandao

on:

  schedule:
    - cron: '27 17 * * *'
  workflow_dispatch:  
jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: requirements
      run: |
        pip install -r requirements.txt
        
    - name: Checkin
      env:
        ONEPUSH: ${{ secrets.ONEPUSH }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python Cloud189Checkin.py

